services:
  # Servicio para inicializar PrestaShop la primera vez
  prestashop-init:
    image: prestashop/prestashop:1.7.8.10
    container_name: prestashop_init
    volumes:
      - ./prestashop:/var/www/html
    command: >
      sh -c "
        if [ ! -f /var/www/html/index.php ]; then
          echo 'Copiando archivos de PrestaShop...';
          cp -r /tmp/prestashop-files/* /var/www/html/ 2>/dev/null ||
          cp -r /var/www/html-original/* /var/www/html/ 2>/dev/null ||
          echo 'Archivos ya presentes';
        else
          echo 'PrestaShop ya inicializado';
        fi
      "
    profiles:
      - init

  db:
    image: mysql:5.7
    container_name: prestashop_mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: prestashop
      MYSQL_USER: prestashop
      MYSQL_PASSWORD: prestashop
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-proot" ]
      interval: 10s
      timeout: 5s
      retries: 5

  prestashop:
    build:
      context: .
      dockerfile: Dockerfile.prestashop
    container_name: prestashop_web
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8080:80"
    environment:
      DB_SERVER: db
      DB_NAME: prestashop
      DB_USER: prestashop
      DB_PASSWD: prestashop
      PS_DEV_MODE: 1
      PS_INSTALL_AUTO: 0
      PS_LANGUAGE: es
      PS_COUNTRY: ES
      ADMIN_MAIL: admin@prestashop.local
      ADMIN_PASSWD: admin123
      # Variables para Xdebug
      XDEBUG_CONFIG: "client_host=host.docker.internal"
      PHP_IDE_CONFIG: "serverName=prestashop-docker"
    volumes:
      - prestashop_data:/var/www/html
      - ./custom-modules:/var/www/html/modules/custom
      - ./custom-themes:/var/www/html/themes/custom
      # Montar logs para debugging
      - ./logs:/var/log
    extra_hosts:
      - "host.docker.internal:host-gateway"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: prestashop_pma
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8081:80"
    environment:
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: root
      UPLOAD_LIMIT: 256M

volumes:
  mysql_data:
  prestashop_data_clean:
